import { ReactNode } from 'react';

export interface ScrollToTopProps {
  children?: ReactNode;
}
export interface TypeDataForm {
  academicAchievements?: string;
  academicAwards?: string;
  applicantSignature?: string;
  assistanceAmount?: string;
  assistanceType?: string;
  careerGoal?: string;
  category?: string;
  consent?: string;
  currentScholarshipsGrants?: string;
  currentSchool?: string;
  declaration?: string;
  dob?: string;
  extracurricularActivities?: string;
  familyIncome?: string;
  financialNeedDescription?: string;
  fullName?: string;
  fundingSource?: string;
  gender?: string;
  grade?: string;
  graduationDate?: string;
  howAssis?: string;
  leadershipPositions?: string;
  major?: string;
  mobile?: string;
  nationality?: string;
  parentNames?: string;
  parentOccupations?: string;
  proofOfIncome?: string;
  recommendationLetters?: string;
  reference1?: string;
  reference2?: string;
  siblingsEducationStatus?: string;
  submissionDate?: string;
  transcripts?: string;
  arrivalDate?: string;
  assistingOrganizations?: string;
  communityConnections?: string;
  employmentHistory?: string;
  employmentStatus?: string;
  familyMembers?: string;
  familyMembersStatus?: string;
  futurePlans?: string;
  generalHealthCondition?: string;
  highestEducationLevel?: string;
  immediateNeeds?: string;
  legalRepresentation?: string;
  medicalCareAccess?: string;
  medicalNeeds?: string;
  nationalId?: string;
  previousCountries?: string;
  reasonForRefugeeStatus?: string;
  references?: string;
  refugeeId?: string;
}
